
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - product-service
      - user-service
      - cart-service
      - order-service
    networks:
      - mynetwork

  product-service:
    build: ./product-service
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - mynetwork

  user-service:
    build: ./user-service
    ports:
      - "8082:8080"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - mynetwork

  cart-service:
    build: ./cart-service
    ports:
      - "8083:8080"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - mynetwork

  order-service:
    build: ./order-service
    ports:
      - "8084:8080"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
